---
databases:
  - db:
      storage: postgresql
      transaction_strategy: dbresolve_readcommitted
      dsn: postgresql://postgres:secret@gcms_dev_pg:5432/guillotina
      read_only: false
      pool_size: 100
store_json: true
applications:
  - guillotina_volto
  - guillotina.contrib.cache
  - guillotina.contrib.catalog.pg
host: 0.0.0.0
address: 8081
static:
  - favicon.png: static/favicon.png
  - assets: guillotina:static/assets
  - swagger_static: guillotina.contrib.swagger:static
root_user:
  password: root
auth_extractors:
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
redis:
  host: localhost
  port: 6379
jwt:
  secret: secret
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
cors:
  allow_origin:
    - '*'
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - OPTIONS
    - PUT
  allow_headers:
    - '*'
  expose_headers:
    - '*'
  allow_credentials: true
  max_age: 3660
global_disallowed_types:
  - User
  - UserManager
  - Group
  - GroupManager
  - Item
  - Container
  - Folder
behaviors:
  myannotationdata:
    title: MyData
    for: guillotina.interfaces.IItem
    inherited_class: guillotina.behaviors.instance.AnnotationBehavior
    properties:
      mydata1:
        type: guillotina.schema.TextLine
        title: Text
        default: Hello
        required: true
  mycontextdata:
    title: MyLocalData
    for: guillotina.interfaces.IItem
    inherited_class: guillotina.behaviors.instance.ContextBehavior
    properties:
      mydata2:
        type: guillotina.schema.TextLine
        title: Text
        default: Hello
contents:
  mydoc:
    title: My Doc
    inherited_interface: guillotina.interfaces.IFolder
    inherited_class: guillotina.content.Folder
    add_permission: guillotina.AddContent
    allowed_types:
      - Image
      - File
    behaviors:
      - guillotina.behaviors.dublincore.IDublinCore
      - guillotina_cms.interfaces.base.ICMSBehavior
      - guillotina_cms.interfaces.blocks.IBlocks
      - guillotina_cms.interfaces.Imycontextdata
    properties:
      json_example:
        type: guillotina.schema.JSONField
        schema:
          type: object
          properties:
            items:
              type: array
        title: My Json Field
      text:
        type: guillotina_cms.fields.richtext.RichTextField
        widget: richtext
        title: Text
        write_permission: guillotina.Manager
        index:
          type: searchabletext
        required: true
      myoption:
        type: guillotina.schema.Choice
        title: My loved option
        vocabulary:
          guillotina: Guillotina
          volto: Volto
        index:
          type: keyword
      mysecondoption:
        type: guillotina.schema.Choice
        title: My loved option
        vocabulary: appsettings:myoptions
        index:
          type: keyword
      mylovedlanguage:
        type: guillotina.schema.Choice
        title: My loved option
        vocabulary: languages
        index:
          type: keyword
      mylovedlist:
        type: guillotina.schema.List
        value_type: guillotina.schema.TextLine
        title: My loved action
        index:
          type: keyword
    fieldsets:
      default:
        - title
        - guillotina.behaviors.dublincore.IDublinCore.description
        - text
        - myoption
        - mysecondoption
        - mylovedlist
        - mylovedlanguage
      dates:
        - guillotina.behaviors.dublincore.IDublinCore.effective_date
        - guillotina.behaviors.dublincore.IDublinCore.expiration_date
      ownership:
        - guillotina.behaviors.dublincore.IDublinCore.creators
        - guillotina.behaviors.dublincore.IDublinCore.publisher
        - guillotina.behaviors.dublincore.IDublinCore.contributors
      categorization:
        - guillotina.behaviors.dublincore.IDublinCore.tags
        - guillotina_cms.interfaces.base.ICMSBehavior.language
      settings:
        - guillotina_cms.interfaces.base.ICMSBehavior.hidden_navigation
        - guillotina_cms.interfaces.base.ICMSBehavior.content_layout
    layouts:
      - document_view
      - layout_view
default_blocks:
  Document:
    blocks:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    blocks_layout:
      items:
      - tile1
      - tile2
      - tile3
  Container:
    blocks:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    blocks_layout:
      items:
        - tile1
        - tile2
        - tile3
myoptions:
  - - guillotina
    - Also Love Guillotina
  - - volto
    - Also Love Volto
allow_discussion_types:
  - Document
