version: '3'
services:
  guillotina:
    build: .
    image: guillotina_volto:local
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app
      - logvolume01:/var/log
    links:
      - postgres
  guillotina-local:
    build: .
    image: guillotina_volto:local
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app
      - ../guillotina:/usr/src/guillotina
      - logvolume01:/var/log
    links:
      - postgres
  postgres:
    image: postgres:12
    container_name: gcms_dev_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_DB: guillotina
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_cms:/var/lib/postgresql/data

volumes:
  logvolume01: {}
  postgres_data_cms: {}
