apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
    aiohttp_settings:
      client_max_size: 20971520
    databases:
    - db:
        storage: postgresql
        transaction_strategy: dbresolve_readcommitted
        dsn: postgresql://{{ .Values.global.postgresql.postgresqlUsername }}:{{ .Values.global.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.postgresqlDatabase }}
        read_only: false
        pool_size: 100
    applications:
    - guillotina_cms
    - guillotina.contrib.dbusers
    - guillotina.contrib.catalog.pg
    - guillotina.contrib.cache
    - guillotina.contrib.swagger
    host: 0.0.0.0
    address: {{ .Values.api.service.internalPort }}
    static:
      favicon.png: static/favicon.png
      assets: guillotina:static/assets
    root_user:
      password: {{ .Values.api.root_passwd }}
    auth_extractors:
    - guillotina.auth.extractors.BearerAuthPolicy
    - guillotina.auth.extractors.BasicAuthPolicy
    - guillotina.auth.extractors.WSTokenAuthPolicy
    auth_token_validators:
    - guillotina.auth.validators.SaltedHashPasswordValidator
    - guillotina.auth.validators.JWTValidator
    jwt:
      secret: {{ .Values.api.jwtsecret }}
      algorithm: HS256
      token_expiration: {{ .Values.api.token_expiration }}
    jsapps:
      +admin: guillotina:static/executioner
    cors:
      allow_origin:
      - "*"
      - "{{ .Values.front.service.externalUrl }}"
      allow_methods:
      - GET
      - POST
      - DELETE
      - HEAD
      - PATCH
      - OPTIONS
      allow_headers:
      - "*"
      expose_headers:
      - "*"
      allow_credentials: true
      max_age: 3660
    {{- toYaml .Values.cms | nindent 4}}
