kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: api
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        role: api
    spec:
      dnsPolicy: ClusterFirst
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.api.tolerations | indent 8 }}
      containers:
      - name: api
        image: "{{ .Values.api.image }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.api.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 90
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.api.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 90
          periodSeconds: 60
        command: ["guillotina", "-c" ,"/app/config.yaml"]
        volumeMounts:
        - mountPath: /app/config.yaml
          name: config
          subPath: config.yaml
        ports:
        - name: api
          containerPort: {{ .Values.api.service.internalPort }}
          protocol: {{ .Values.api.service.protocol }}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-config
