name: guillotina

on: [push]

jobs:

  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install flake8==3.7.7
          pip install mypy==0.720
          pip install mypy-zope==0.2.0
          pip install black==19.10b0
          pip install isort==4.3.21
      - name: Run pre-checks
        run: |
          flake8 guillotina_volto --config=setup.cfg
          mypy guillotina_volto/ --ignore-missing-imports
          black --check --verbose guillotina_volto
  # Job to run tests
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        database: ["DUMMY", "postgres"]

    # Set environment variables
    env:
      DATABASE: ${{ matrix.database }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the package
        run: |
          pip install $(grep "Cython" requirements.txt)
          pip install -r requirements.txt
          pip install -r contrib-requirements.txt
          pip install -r requirements-test.txt
          pip install -e .

      - name: Run tests
        run: |
          pytest -rfE --reruns 2 --cov=guillotina -s --tb=native -v --cov-report xml --cov-append guillotina_volto

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
